// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaMT4mTavlaMC6ROQZNjf6XAA1eejfRH4',
    appId: '1:248980108990:web:079024a3c919da77e550ef',
    messagingSenderId: '248980108990',
    projectId: 'club-india-user',
    authDomain: 'club-india-user.firebaseapp.com',
    storageBucket: 'club-india-user.firebasestorage.app',
    measurementId: 'G-JGN5YXR8QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1ZDUkmU00ypA66K0j9dkHghv_JVuuNPg',
    appId: '1:248980108990:android:f7fec79ff0db1252e550ef',
    messagingSenderId: '248980108990',
    projectId: 'club-india-user',
    storageBucket: 'club-india-user.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB55ds6TrgU2vYaB9ELlJJs-JeplwWDUs4',
    appId: '1:248980108990:ios:7ed6f42690099fafe550ef',
    messagingSenderId: '248980108990',
    projectId: 'club-india-user',
    storageBucket: 'club-india-user.firebasestorage.app',
    iosBundleId: 'com.example.clubIndiaUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB55ds6TrgU2vYaB9ELlJJs-JeplwWDUs4',
    appId: '1:248980108990:ios:7ed6f42690099fafe550ef',
    messagingSenderId: '248980108990',
    projectId: 'club-india-user',
    storageBucket: 'club-india-user.firebasestorage.app',
    iosBundleId: 'com.example.clubIndiaUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaMT4mTavlaMC6ROQZNjf6XAA1eejfRH4',
    appId: '1:248980108990:web:a93471891871f0e7e550ef',
    messagingSenderId: '248980108990',
    projectId: 'club-india-user',
    authDomain: 'club-india-user.firebaseapp.com',
    storageBucket: 'club-india-user.firebasestorage.app',
    measurementId: 'G-6TXK4GLWFZ',
  );
}
