// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlSJOnL_kjIHZJtMJzxLmp0RrJ3qgZ2zA',
    appId: '1:713808133886:web:2e2f866768ffdaa7142faf',
    messagingSenderId: '713808133886',
    projectId: 'clubindia-rewards',
    authDomain: 'clubindia-rewards.firebaseapp.com',
    storageBucket: 'clubindia-rewards.firebasestorage.app',
    measurementId: 'G-DK584P8TKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqPXwkF6_CIVSYhWZ8iUgVrC-BWmnctiQ',
    appId: '1:713808133886:android:8a45617a168cabc8142faf',
    messagingSenderId: '713808133886',
    projectId: 'clubindia-rewards',
    storageBucket: 'clubindia-rewards.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvRYzkjSySIfqODE6S1WMSp0ZxAbIFMYY',
    appId: '1:713808133886:ios:a11c1393f90edfec142faf',
    messagingSenderId: '713808133886',
    projectId: 'clubindia-rewards',
    storageBucket: 'clubindia-rewards.firebasestorage.app',
    iosBundleId: 'com.example.clubIndiaUser',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvRYzkjSySIfqODE6S1WMSp0ZxAbIFMYY',
    appId: '1:713808133886:ios:a11c1393f90edfec142faf',
    messagingSenderId: '713808133886',
    projectId: 'clubindia-rewards',
    storageBucket: 'clubindia-rewards.firebasestorage.app',
    iosBundleId: 'com.example.clubIndiaUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlSJOnL_kjIHZJtMJzxLmp0RrJ3qgZ2zA',
    appId: '1:713808133886:web:9776048671e02281142faf',
    messagingSenderId: '713808133886',
    projectId: 'clubindia-rewards',
    authDomain: 'clubindia-rewards.firebaseapp.com',
    storageBucket: 'clubindia-rewards.firebasestorage.app',
    measurementId: 'G-BYGNGBREGV',
  );
}
